---
- name: Deploy Web Applications
  hosts: node1
  gather_facts : yes
  tasks:

    - package :
        name: httpd
        state: latest

    - service :
        name: httpd
        enabled: yes
        state: started

    - name: Create a custom index.html file
      copy:
        dest: /var/www/html/index.html
        content: "{{ web_message }}"
